# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 15:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayResponse',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Ultima modificación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, default='Created', max_length=25, null=True, verbose_name='Estado')),
                ('response_code', models.IntegerField(blank=True, default=0, null=True, verbose_name='Codigo de respuesta')),
                ('raw', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Respuesta de la pasarela')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Ultima modificación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='descripción')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.Operation')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cantidad')),
            ],
            options={
                'abstract': False,
            },
            bases=('payments.operation',),
        ),
        migrations.AddField(
            model_name='gatewayresponse',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='payments.Operation'),
        ),
    ]
