# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('Authorization', 'authorization'), ('Authorization and Capture', 'authorization-and-capture'), ('Refund', 'refund'), ('Void', 'void'), ('Capture', 'capture')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor'),
        ),
    ]
