# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Ultima modificación')),
                ('method', models.CharField(choices=[('GET', 'get'), ('POST', 'post'), ('DELETE', 'delete'), ('PUT', 'put'), ('PATCH', 'patch')], default='POST', max_length=6)),
            ],
            options={
                'ordering': ['-creation_date'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='APICalls',
        ),
    ]
