# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apicall_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='view',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='method',
            field=models.CharField(choices=[('GET', 'get'), ('POST', 'post'), ('DELETE', 'delete'), ('PUT', 'put'), ('PATCH', 'patch')], default='GET', max_length=6),
        ),
    ]
