# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 00:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Ultima modificación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, default='Created', max_length=25, null=True, verbose_name='Estado')),
                ('response_code', models.IntegerField(blank=True, default=0, null=True, verbose_name='Codigo de respuesta')),
                ('raw', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Respuesta')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='operations.Operation')),
            ],
            options={
                'ordering': ['-creation_date'],
                'abstract': False,
            },
        ),
    ]
