# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import transactions.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Ultima modificación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-creation_date'],
                'abstract': False,
            },
            bases=(transactions.mixins.OperationManagerMixin, models.Model),
        ),
    ]
