# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Ultima modificación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-creation_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='transactions.Transaction')),
            ],
            options={
                'ordering': ['-creation_date'],
                'abstract': False,
            },
            bases=('operations.operation', models.Model),
        ),
        migrations.CreateModel(
            name='AuthorizationAndCapture',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations_and_captures', to='transactions.Transaction')),
            ],
            options={
                'verbose_name_plural': 'Authorizations and Captures',
            },
            bases=('operations.operation', models.Model),
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='transactions.Transaction')),
            ],
            options={
                'ordering': ['-creation_date'],
                'abstract': False,
            },
            bases=('operations.operation', models.Model),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='transactions.Transaction')),
            ],
            options={
                'ordering': ['-creation_date'],
                'abstract': False,
            },
            bases=('operations.operation', models.Model),
        ),
        migrations.CreateModel(
            name='Void',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.Operation')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voids', to='transactions.Transaction')),
            ],
            options={
                'ordering': ['-creation_date'],
                'abstract': False,
            },
            bases=('operations.operation',),
        ),
    ]
