# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizationandcapture',
            options={'verbose_name': 'Authorization and Capture', 'verbose_name_plural': 'Authorizations and Captures'},
        ),
    ]
